### ISSUE TITLE
Some questions about running

### ISSUE THREAD

**Issue by LoveUSimone** [H2SO4T/ARES#13]
Hi, thanks for your good job.
I use the instruction:
"python parallel_exec.py --instr_jacoco --real_device --udids "e62b6cf8" --list_device "qualcomm1" --appium_ports "4270" --android_ports "5554" --path "D:\apk/" --timer 70 --rotation --internet --platform_version 12.0 --iterations 2 --algo SAC --timesteps 5000 --trials_per_app 1"
But it come into errors about 
"ERROR: The process "node.exe" not found.
Traceback (most recent call last):
  File "parallel_exec.py", line 132, in <module>
    main()
  File "parallel_exec.py", line 126, in main
    processes.append(subprocess.Popen(cmd))
  File "D:\Python3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Python3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified "
Do you konw why is that ? Thanks a lot.

**Comment by H2SO4T** [comment]
Hi, 
to make ARES work, you need to install appium and Node.js
