### ISSUE TITLE
Cannot start the 'com.android.insecurebankv2' application

### ISSUE THREAD

**Issue by x4evexnol** [H2SO4T/ARES#17]
android version: 8.1
error happend when I run with the cmd: python test_application.py --instr_emma --appium_port "4723" --android_port "62002" --timer 10 --rotation --internet --emu normal --platform_version "8.1" --iterations 2 --algo random --timesteps 50 --trials_per_app 3 --apps "D:\code\pycharm\gym\test\test_resources\InsecureBankv2.apk" --save_policy

![image-20221018212644209](https://user-images.githubusercontent.com/67748962/196444377-ea71c5d9-7e41-47b9-b80a-1b075c6e374a.png)

**Comment by x4evexnol** [comment]
I have successfully instrumented the InsecureBankv2

**Comment by H2SO4T** [comment]
Hi,
This is not a problem related to ARES. This is an application problem (it crashes) 😅
Moreover, if you used cosmo the correct flag to use is --instr_jacoco

**Comment by Yu-Han-98** [comment]
Same error

**Comment by x4evexnol** [comment]
Can I use the my apps for testing?

**Comment by PradarshOmdsana** [comment]
same error

**Comment by H2SO4T** [comment]
@shiyuanxiang yes you can use any app you want, however the InsecureBank crash is not related to ARES.
I suggest you to investigate the crash causes using Logcat
for example: https://f-droid.org/docs/Getting_logcat_messages_after_crash/
