### ISSUE TITLE
Reload a previously learned navigation policy

### ISSUE THREAD

**Issue by Searcher408** [H2SO4T/ARES#3]
Hello, I am reproducing this project. Could you please update the module about reloading a previously learned navigation policy? And how to use the FATE trained models?

**Comment by H2SO4T** [comment]
Hello, thank you for trying my tool ARES. I have just submitted the "reload-policy" module (please see the readme for more details). 

Speaking about FATE, you need to modify the code inserting the hyper-parameters you want to test, and launch the scripts on your models. Once done, you need to compare the results, finding which combination of hyper-parameters is best for your scenario. At last, you can "port" the best hyper-parameters in ARES by modifying the script SACExploration.py.
You can look for the hyper-parameters on the documentation StableBaselines: https://stable-baselines.readthedocs.io/en/master/modules/sac.html

**Comment by Searcher408** [comment]
Thank you very much for your detailed reply, it helps a lot.
