### ISSUE TITLE
where can I get your app benchmark ?

### ISSUE THREAD

**Issue by DMJ1997** [H2SO4T/ARES#4]
hi, it‘s quiet a good job! can you share your app benchmark ?
I also try to build app by cosmo, but it didn't work for some android source code.
Github project VinylMusicPlayer is buided success after cosmo, but it didn't generate converge files after using "adb shell am broadcast -p com.poupa.vinylmusicplayer -a intent.END_COVERAGE". Do you know why is that?
Thanks a lot.

**Comment by H2SO4T** [comment]
Hy @DMJ1997 thank you :)
As written in the paper, the benchmark apps come from AndroTest: http://bear.cc.gatech.edu/~shauvik/androtest/

Moreover, COSMO works on `VinylMusicPlayer`. You are simply missing the correct package name of the app (a debug apk), that is  `com.poupa.vinylmusicplayer.ci.debug`. Launching `adb shell am broadcast -p com.poupa.vinylmusicplayer.ci.debug -a intent.END_COVERAGE` the app generates the coverage file as expected.
