### ISSUE TITLE
Some quetions about app experiment

### ISSUE THREAD

**Issue by Tangsuuu** [H2SO4T/ARES#7]
Hi, thanks for your good job. 
I have questions about the 'Experimental Results: Study 2' in your paper. 
The results are obtained during training or testing? Is it necessary to load the pretrained model to test after training the model?
The results are obtained using one hour or 4000 steps ?  And how many steps is runing within one hour in your experiment if the results is obtained using one hour.

I'm trying to use SAC of ARES to test apps(Markor and MicroMathematics).
The first item of action_number is tent always to be zero or one after 1125 steps(generate 45 converage files) .
I use the instruction:
python3 parallel_exec.py --instr_jacoco --list_devices "gtestapi27" --appium_ports "4270" --android_ports "5554" --path "apps" --timer 60 --rotation --internet --emu normal --platform_version 8.1 --iterations 10 --algo SAC --timesteps 5000 --trials_per_app 3
Do you konw why is that ? Thanks a lot.

**Comment by H2SO4T** [comment]
Hello, thank you for trying ARES. 
I will investigate the problem in the next few days.

I'll keep you updated.

**Comment by H2SO4T** [comment]
To answer the questions:

1) The results are obtained during the training phase; we have never used the pre-trained model during the study. The purpose of reloading a policy is to boost the exploration of an app already tested. 

2) The results are obtained using one hour of testing and setting 4000 steps as the maximum limit of steps. ARES will stop the app testing if it reaches the one-hour testing limit.

**Comment by Tangsuuu** [comment]
> To answer the questions:
> 
> 1. The results are obtained during the training phase; we have never used the pre-trained model during the study. The purpose of reloading a policy is to boost the exploration of an app already tested.
> 2. The results are obtained using one hour of testing and setting 4000 steps as the maximum limit of steps. ARES will stop the app testing if it reaches the one-hour testing limit.

I also try to test markor using random policy in ARES. Is it the same project(https://github.com/gsantner/markor) in your paper?
And I just find one-hour testing limit code(while not t.timer_expired():) in RandomExploration.py file. Steps limit sames don't work. 
I also don't find collect_coverage_jacoco code in RandomExploration.py file and I add the collect_coverage_jacoco code to generate coverage files by myself.
I finally get 50.7% average coverage using 6000steps in 10 runs and 47.8% average coverage using 4000steps in 10 runs.
50.7% average coverage is close to the result(markor) in paper. So I guess random policy ran about 6000 steps in an hour.

**Comment by H2SO4T** [comment]
> 
> I also try to test markor using random policy in ARES. Is it the same project(https://github.com/gsantner/markor) in your paper? 

Yes, but I have tested the 2019th version (I don't remember which one)

>And I just find one-hour testing limit code(while not t.timer_expired():) in RandomExploration.py file. Steps limit sames don't work. I also don't find collect_coverage_jacoco code in RandomExploration.py file and I add the collect_coverage_jacoco code to generate coverage files by myself. I finally get 50.7% average coverage using 6000steps in 10 runs and 47.8% average coverage using 4000steps in 10 runs. 50.7% average coverage is close to the result(markor) in paper. So I guess random policy ran about 6000 steps in an hour.

I will fix the issues. Thank you for notifying me  ☺️
