### ISSUE TITLE
ARES seems blocked

### ISSUE THREAD

**Issue by Yu-Han-98** [H2SO4T/ARES#9]
Hi @H2SO4T ,
First of all thanks for the very interesting and useful project.

However, after your update, it stopped working on some applications.

My setup is based on python3.9 and a Macbook PRO M1 Max with 32GB of RAM.

I have tested the tool with different applications and it works perfectly.
However, with some apps, it gets stuck and doesn't seem to find and perform the actions to do.

Can I upload one of the apps that give me this kind of problem?

**Comment by H2SO4T** [comment]
Dear @Yu-Han-98, yes, feel free to share with me all the apps that get stuck.
Unfortunately, I will not be very fast in the possible fix due to pending work.

**Comment by Yu-Han-98** [comment]
@H2SO4T really thank you.

I just upload the apk on my repository [debug.apk](https://github.com/Yu-Han-98/Test-Apk-Ares/blob/main/debug.apk).

**Comment by 0xdad0** [comment]
anche a me si blocca

**Comment by 0xdad0** [comment]
@H2SO4T
